big reorganization for change to rc

diff --git a/sjfs-chat b/sjfs-chat
--- a/sjfs-chat
+++ b/sjfs-chat
@@ -1,56 +1,64 @@
-#!/bin/sh
+#!/usr/bin/env rc
 # Ctrl-D to end
-set -eu
-: "${DEBUG:=}"
-[ -n "$DEBUG" ] && set -x
+flag e +
+~ $DEBUG ?* && flag x +
 
-usage="usage: $(basename $0) [-dsu] [-c | -b buddy]
+usage='usage: ' ^ `{basename $0} ^ ' [-dsu] [-c | -b buddy]
 -c: chat in current directory, expecting in and out files to exist
 -b: chat with specified buddy
 See sj(1) for explanation of options d, s, and u.
-Environment variables:  all from sj(1) and style, color, note_time"
+Environment variables:  all from sj(1) and style, color, note_time'
 
 # Set configuration variable to "no" to disable feature
 #
 # style of incming message:  a style for tput e.g. bold, dim, blink, smul
 # (underlined), rev (reverse), smso (standout)
-: "${style:=no}"
+~ $style ?* || style=no
 # color of incoming message:  a color for tput setaf, e.g. 1-7
-: "${color:=1}"
+~ $color ?* || color=1
 # number of milliseconds for the notify-send timeout
-: "${note_time:=500}"
+~ $note_time ?* || note_time=500
 
-: "${SJ_DIR:=}"
-: "${SJ_SERVER:=}"
-: "${SJ_USER:=}"
+current_dir=''  # initialize variables
+buddy=''
+state=''
+for (arg) {
+	if(~ $state ?*) {
+		switch($state) {
+		case -d; SJ_DIR=$arg
+		case -s; SJ_SERVER=$arg
+		case -u; SJ_USER=$arg
+		case -b; buddy=$arg
+		}
+		state=''
+	}
+	if not {
+		switch($arg) {
+		case -[dsub]; state=$arg
+		case -c; current_dir=yes
+		case *
+			printf '%s: invalid option: %s\n%s\n' `{basename $0} $arg $usage
+			exit 1
+		}
+	}
+}
 
-current_dir=""  # initialize variables
-buddy=""
-while [ $# -gt 0 ]; do
-	case "$1" in
-		-d) [ -n "$2" ] && SJ_DIR="$2"; shift;;
-		-s) [ -n "$2" ] && SJ_SERVER="$2"; shift;;
-		-u) [ -n "$2" ] && SJ_USER="$2"; shift;;
-		-b) [ -n "$2" ] && buddy="$2"; shift;;
-		-c) current_dir=yes ;;
-		*)  printf "$(basename $0): invalid option $1\n$usage\n"; exit 1;;
-	esac
-	shift
-done
-
-if [ -z "$current_dir" ]; then
-	[ -n "$SJ_DIR" ] || { echo Directory is needed via -d or SJ_DIR; exit 1; }
-	[ -n "$buddy" ] || { echo Buddy is needed via -b; exit 1; }
-	cd "$SJ_DIR"/"$buddy" || { echo cannot cd to "$SJ_DIR"/"$buddy"; exit 1; }
-fi
-
+if(! ~ $current_dir ?*) {
+	~ $SJ_DIR ?* || { echo Directory is needed via -d or SJ_DIR; exit 1; }
+	~ $buddy ?* || { echo Buddy is needed via -b; exit 1; }
+	cd $SJ_DIR/$buddy || { echo cannot cd to $SJ_DIR/$buddy; exit 1; }
+}
 [ -e out ] || { echo out file required; exit 1; }
 [ -p in ] || { echo in file required and must be a named pipe; exit 1; }
 cat out  # show the conversation so far
 
-export style color note_time SJ_USER SJ_SERVER
 sjfs-monitor-outfile out &
-trap "/bin/kill -TERM -$$" HUP INT QUIT TERM EXIT  # kill the background job
+bg_job=$apid
+fn sigint  { kill -TERM -$bg_job } # kill the background job
+fn sigquit { kill -TERM -$bg_job }
+fn sighup  { kill -TERM -$bg_job }
+fn sigterm { kill -TERM -$bg_job }
+fn sigexit { kill -TERM -$bg_job }
 
 cat > in  # Ctrl-D to end
-/bin/kill -TERM -$$  # kill the background job
+kill -TERM -$bg_job # kill the background job
diff --git a/sjfs-monitor-all-chats b/sjfs-monitor-all-chats
--- a/sjfs-monitor-all-chats
+++ b/sjfs-monitor-all-chats
@@ -1,63 +1,69 @@
-#!/bin/sh
-set -eu
-: "${DEBUG:=}"
-[ -n "$DEBUG" ] && set -x
+#!/usr/bin/env rc
+flag e +
+~ $DEBUG ?* && flag x +
 
-usage="usage: $(basename $0) [-d <directory>]
-Environment variables:  SJ_DIR, SJ_SERVER, SJ_USER"
+usage='usage: ' ^ `{basename $0} ^ ' [-d <directory>]
+Environment variables:  SJ_DIR, SJ_SERVER, SJ_USER'
 
 # Set configuration variable to "no" to disable feature
 #
 # number of milliseconds for the notify-send timeout
-: "${note_time:=no}"
+~ $note_time ?* || note_time=no
 
-: "${SJ_DIR:=}"
-: "${SJ_SERVER:=}"
-: "${SJ_USER:=}"
+state=''
+for (arg) {
+	if(~ $state ?*) {
+		switch($state) {
+		case -d; SJ_DIR=$arg
+		case -s; SJ_SERVER=$arg
+		case -u; SJ_USER=$arg
+		}
+		state=''
+	}
+	if not {
+		switch($arg) {
+		case -[dsu]; state=$arg
+		case *
+			printf '%s: invalid option: %s\n%s\n' `{basename $0} $arg $usage
+			exit 1
+		}
+	}
+}
 
-while [ $# -gt 0 ]; do
-	case "$1" in
-		-d) SJ_DIR="$2"; shift;;
-		-s) SJ_SERVER="$2"; shift;;
-		-u) SJ_USER="$2"; shift;;
-		*)  printf "$(basename $0): invalid option $1\n$usage\n"; exit 1;;
-	esac
-	shift
-done
+~ $SJ_DIR ?* || { echo Directory is needed via -d or SJ_DIR; exit 1; }
+cd $SJ_DIR || { echo cannot cd to $SJ_DIR; exit 1; }
 
-[ -n "$SJ_DIR" ] || { echo Directory is needed via -d or SJ_DIR; exit 1; }
-cd "$SJ_DIR" || { echo cannot cd to "$SJ_DIR"; exit 1; }
+bg_jobs=()
+outs1=`{find . -name out | sort}
+if (~ $outs1 ?*) {
+	for (o in $outs1) {
+		style=no color=no sjfs-monitor-outfile $o &
+		bg_jobs=($bg_jobs $apid)
+	}
+}
 
-outs1=`find . -name out | sort`
-if [ -n "$outs1" ]; then
-	for o in $outs1; do
-		export note_time SJ_USER SJ_SERVER
-		style=no color=no sjfs-monitor-outfile "$o" &
-	done
-fi
+fn sigint  { for (job in $bg_jobs) kill -TERM -$job; exit 1 }
+fn sigquit { for (job in $bg_jobs) kill -TERM -$job; exit 2 }
+fn sighup  { for (job in $bg_jobs) kill -TERM -$job; exit 3 }
+fn sigterm { for (job in $bg_jobs) kill -TERM -$job; exit 4 }
+fn sigexit { for (job in $bg_jobs) kill -TERM -$job; exit 5 }
 
-trap "/bin/kill -TERM -$$" HUP INT QUIT TERM EXIT  # kill all background jobs
-
-while true; do
+while (true) {
 	# entr waits for a change in directories within $SJ_DIR.
 	# 1st true is because entr needs a utility.
 	# 2nd true prevents an error in this script since entr returns 2.
 	find . -type d | entr -pd true || true
-	outs2=`find . -name out | sort`
-	if [ "$outs1" != "$outs2" ] ; then
-		o1f=$(mktemp) || exit 1 && echo "$outs1" > "$o1f"
-		o2f=$(mktemp) || exit 1 && echo "$outs2" > "$o2f"
-		new_outs=`comm -13 "$o1f" "$o2f"`
-		rm "$o1f" "$o2f"
-		for o in $new_outs; do
-			notice="new chat from $(basename $(dirname $o))"
-			printf "$notice\a\n"
-			[ "$note_time" != no ] && notify-send -t "$note_time" "sjfs-monitor" "$notice"
-			cat "$o"
-			export note_time SJ_USER SJ_SERVER
-			style=no color=no sjfs-monitor-outfile "$o" &
-		done
-		outs1="$outs2"
-	fi
-done
-/bin/kill -TERM -$$
+	outs2=`{find . -name out | sort}
+	if ( ! ~ $"outs1 $"outs2 ) {
+		new_outs=`{comm -13 <{for (s in $outs1) echo $s} <{for (s in $outs2) echo $s} }
+		for (o in $new_outs) {
+			notice='new chat from ' ^ `{basename `{dirname $o}}
+			printf $notice ^ '\a\n'
+			~ $note_time no || notify-send -t $note_time sjfs-monitor $notice
+			cat $o
+			style=no color=no sjfs-monitor-outfile $o &
+			bg_jobs=($bg_jobs $apid)
+		}
+		outs1=$outs2
+	}
+}
diff --git a/sjfs-online-buddies b/sjfs-online-buddies
--- a/sjfs-online-buddies
+++ b/sjfs-online-buddies
@@ -1,42 +1,45 @@
-#!/bin/sh
-set -eu
-: "${DEBUG:=}"
-[ -n "$DEBUG" ] && set -x
+#!/usr/bin/env rc
+flag e +
+~ $DEBUG ?* && flag x +
 
-usage="usage: $(basename $0) [-d <directory>]
+usage='usage: ' ^ `{basename $0} ^ ' [-d <directory>]
 Run this command with watch for extra functionality.
 Environment variables:  SJ_DIR
-"
+'
 
-: "${SJ_DIR:=}"
+switch($#*) {
+case 0
+	true # do nothing
+case 2
+	if (~ $1 -d) SJ_DIR=$2
+	if not {
+		printf '%s: invalid option: %s\n%s' `{basename $0} $1 $usage
+		exit 1
+	}
+case *
+	printf '%s: wrong number of arguments\n%s' `{basename $0} $usage
+	exit 1
+}
 
-while [ $# -gt 0 ]; do
-	case "$1" in
-		-d) SJ_DIR="$2"; shift;;
-		*)  printf "$(basename $0): invalid option $1\n$usage"; exit 1;;
-	esac
-	shift
-done
-
-[ -n "$SJ_DIR" ] || { echo Directory is needed via -d or SJ_DIR; exit 1; }
-cd "$SJ_DIR" || { echo cannot cd to "$SJ_DIR"; exit 1; }
+~ $SJ_DIR ?* || { echo Directory is needed via -d or SJ_DIR; exit 1; }
+cd $SJ_DIR || { echo cannot cd to $SJ_DIR; exit 1; }
 pgrep presenced >/dev/null || { echo no presenced; exit 1; }
 
-status_files="$(find . -maxdepth 2 -name status)"
-if [ -n "$status_files" ]; then
+status_files=`{find . -maxdepth 2 -name status}
+if (~ $status_files ?*)
 	egrep '.+' $status_files | sed 's|^\./||g' | sed 's|/status:|:\t|g'
-else
+if not {
 	echo No status files found
 	exit 1
-fi
+}
 
 echo
 echo Offline Buddies
 echo ---------------
-for f in *; do
-	if [ -d "$f" ]; then
-		if [ ! -s "$f"/status ]; then
-			echo "$f"
-		fi
-	fi
-done
+for (f in *) {
+	if ([ -d $f ]) {
+		if ([ ! -s $f/status ]) {
+			echo $f
+		}
+	}
+}
